Repository snxd/proxyres, pull requests merged in 2023-12, with the labels that each got.

#54 winrt: net_adapter functions do not require PROXYRES_EXECUTE
  CMakeLists.txt
  net_adapter_win.c
Labels: bug

#56 Fixed bugs with enumerating network adapters on macOS
  net_adapter_mac.c
Labels: bug

#58 Add support for ipv6 addresses to net_adapter.
  net_adapter.c
  net_adapter.h
  net_adapter_linux.c
  net_adapter_mac.c
  net_adapter_win.c
Labels: enhancement

#60 Convert line-endings to LF.
  .github/workflows/macos.yaml
  .github/workflows/ubuntu.yaml
  .github/workflows/win32.yaml
  execute_wsh_dispatch.h
  execute_wsh_site.h
  test/test_net_util.cc
Labels: cleanup
