Repository snxd/proxyres, pull requests merged in 2023-01, with the labels that each got.

#7 Switch to clang-format-15
  .github/workflows/lint.yaml
Labels: continuous integration

#8 Call pthread_exit() instead of return in pthread start functions
  threadpool_pthread.c
Labels: good first issue

#10 Fixed more compilation warnings in threadpool_winxp
  threadpool_winxp.c
Labels: warnings fix
