Repository snxd/proxyres, pull requests merged in 2023-02, with the labels that each got.

#13 Add the ability to configure empty bypass list for avoiding proxy bypass
  config.c
  doc/proxy_config.md
Labels: enhancement

#14 Remove explicit boolean checks in if statements.
  config_mac.c
Labels: cleanup

#15 Add test case for the empty proxy bypass list configured
  test/test_config.cc
Labels: continuous integration

#19 Fixed missing include for strcasecmp and _strnicmp in curl example.
  test/curl_proxyres.c
Labels: bug

#17 Fixed memory leak in should_bypass_proxy during early exit.
  util.c
Labels: bug

#20 Revert "Add the ability to configure empty bypass list for avoiding proxy bypass"
  config.c
  doc/proxy_config.md
Labels: bug

#21 Added link to win proxy behavior table for local addresses.
  README.md
Labels: documentation

#23 Check for empty string when setting proxy override settings.
  config.c
Labels: enhancement

#24 Don't return empty values in proxy_config functions.
  config_gnome2.c
  config_mac.c
Labels: cleanup

#26 Added support proxy bypass rule with IP CIDR notation.
  test/test_util.cc
  util.c
  util_win.c
  util_win.h
Labels: enhancement

#28 Added support for proxy bypass rules with IPv6 CIDR notation.
  test/test_util.cc
  util.c
  util.h
Labels: enhancement

#31 Fixed proxy bypass list override test when override is empty string.
  test/test_config.cc
Labels: unit tests
