Repository snxd/proxyres, pull requests merged in 2024-12, with the labels that each got.

#77 SPTCH-3534: Use already loaded version of JSCoreGTK if available
  execute_jscore.c
Labels: bug

#80 Add support for KDE6.
  util_linux.c
Labels: enhancement

#83 jscore: fix JSCoreGTK version conflict w/ loaded one by user app
  execute_jscore.c
Labels: bug

#84 fix: not working JSCoreGTK proxy_execute_* after global reinitialization
  execute_jscore.c
Labels: bug

#82 Add support for libjavascriptcoregtk-6.0.
  .github/workflows/ubuntu.yaml
  CMakeLists.txt
  execute.c
  execute_jsc.c
  execute_jsc.h
  execute_jscore.c
Labels: dependencies
